import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vidumini's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="min-h-screen flex flex-col mx-32 mt-8">
        <Navbar/>
        <main className="flex-1">{children}</main>
      
      </body>
    </html>
  );
}
